<?php

namespace Database\Seeders;

use App\Models\Personnel;
use App\Models\User;
use Illuminate\Database\Seeder;

/**
 * Seeder pour créer des fiches personnel de test
 */
class PersonnelSeeder extends Seeder
{
    /**
     * Exécuter le seeding
     */
    public function run(): void
    {
        // Créer 30 membres du personnel avec des données réalistes
        $personnel = [
            // Service Dialyse
            [
                'first_name' => 'Marie',
                'last_name' => 'Dubois',
                'job_title' => 'Chef de Service',
                'specialty' => 'Néphrologie',
                'department' => 'Dialyse',
                'employment_type' => 'full_time',
                'email_pro' => 'marie.dubois@dispodialyse.fr',
                'phone_office' => '0123456701',
                'phone_mobile' => '0612345601',
                'extension' => '101',
                'qualifications' => ['DES Néphrologie', 'Master Santé Publique'],
                'certifications' => ['Formation Dialyse Avancée', 'Gestion d\'équipe'],
                'languages' => ['Français', 'Anglais'],
                'hire_date' => '2010-03-15',
                'is_active' => true,
            ],
            [
                'first_name' => 'Pierre',
                'last_name' => 'Martin',
                'job_title' => 'Médecin',
                'specialty' => 'Néphrologie',
                'department' => 'Dialyse',
                'employment_type' => 'full_time',
                'email_pro' => 'pierre.martin@dispodialyse.fr',
                'phone_office' => '0123456702',
                'phone_mobile' => '0612345602',
                'extension' => '102',
                'qualifications' => ['DES Néphrologie', 'DIU Dialyse'],
                'certifications' => ['Formation Hémodialyse', 'Urgences Rénales'],
                'languages' => ['Français', 'Anglais', 'Espagnol'],
                'hire_date' => '2015-09-01',
                'is_active' => true,
            ],
            [
                'first_name' => 'Sophie',
                'last_name' => 'Bernard',
                'job_title' => 'Cadre de Santé',
                'department' => 'Dialyse',
                'employment_type' => 'full_time',
                'email_pro' => 'sophie.bernard@dispodialyse.fr',
                'phone_office' => '0123456703',
                'phone_mobile' => '0612345603',
                'phone_pager' => '1234',
                'extension' => '103',
                'qualifications' => ['IDE', 'Master Management Santé'],
                'certifications' => ['Cadre de Santé', 'Gestion des Soins'],
                'languages' => ['Français', 'Anglais'],
                'hire_date' => '2012-01-10',
                'is_active' => true,
            ],
            [
                'first_name' => 'Lucas',
                'last_name' => 'Petit',
                'job_title' => 'Infirmier',
                'department' => 'Dialyse',
                'employment_type' => 'full_time',
                'email_pro' => 'lucas.petit@dispodialyse.fr',
                'phone_office' => '0123456704',
                'phone_mobile' => '0612345604',
                'extension' => '104',
                'qualifications' => ['Diplôme IDE', 'DU Dialyse'],
                'certifications' => ['Hémodialyse', 'Dialyse Péritonéale'],
                'languages' => ['Français'],
                'hire_date' => '2018-06-01',
                'is_active' => true,
            ],
            [
                'first_name' => 'Emma',
                'last_name' => 'Robert',
                'job_title' => 'Infirmier',
                'department' => 'Dialyse',
                'employment_type' => 'full_time',
                'email_pro' => 'emma.robert@dispodialyse.fr',
                'phone_office' => '0123456705',
                'phone_mobile' => '0612345605',
                'extension' => '105',
                'qualifications' => ['Diplôme IDE'],
                'certifications' => ['Hémodialyse'],
                'languages' => ['Français', 'Arabe'],
                'hire_date' => '2019-09-15',
                'is_active' => true,
            ],
            [
                'first_name' => 'Thomas',
                'last_name' => 'Richard',
                'job_title' => 'Infirmier',
                'department' => 'Dialyse',
                'employment_type' => 'full_time',
                'email_pro' => 'thomas.richard@dispodialyse.fr',
                'phone_mobile' => '0612345606',
                'extension' => '106',
                'qualifications' => ['Diplôme IDE', 'DU Soins Critiques'],
                'certifications' => ['Hémodialyse', 'Urgences'],
                'languages' => ['Français', 'Anglais'],
                'hire_date' => '2017-03-20',
                'is_active' => true,
            ],
            [
                'first_name' => 'Julie',
                'last_name' => 'Durand',
                'job_title' => 'Aide-Soignant',
                'department' => 'Dialyse',
                'employment_type' => 'full_time',
                'email_pro' => 'julie.durand@dispodialyse.fr',
                'phone_mobile' => '0612345607',
                'extension' => '107',
                'qualifications' => ['Diplôme AS'],
                'languages' => ['Français', 'Portugais'],
                'hire_date' => '2020-01-15',
                'is_active' => true,
            ],
            [
                'first_name' => 'Alexandre',
                'last_name' => 'Moreau',
                'job_title' => 'Aide-Soignant',
                'department' => 'Dialyse',
                'employment_type' => 'part_time',
                'email_pro' => 'alexandre.moreau@dispodialyse.fr',
                'phone_mobile' => '0612345608',
                'qualifications' => ['Diplôme AS'],
                'languages' => ['Français'],
                'hire_date' => '2021-06-01',
                'is_active' => true,
            ],
            [
                'first_name' => 'Camille',
                'last_name' => 'Simon',
                'job_title' => 'Secrétaire Médicale',
                'department' => 'Dialyse',
                'employment_type' => 'full_time',
                'email_pro' => 'camille.simon@dispodialyse.fr',
                'phone_office' => '0123456709',
                'extension' => '109',
                'qualifications' => ['BTS Secrétariat Médical'],
                'languages' => ['Français', 'Anglais'],
                'hire_date' => '2016-11-01',
                'is_active' => true,
            ],
            [
                'first_name' => 'Nicolas',
                'last_name' => 'Laurent',
                'job_title' => 'Technicien Biomédical',
                'department' => 'Dialyse',
                'employment_type' => 'full_time',
                'email_pro' => 'nicolas.laurent@dispodialyse.fr',
                'phone_office' => '0123456710',
                'phone_mobile' => '0612345610',
                'extension' => '110',
                'qualifications' => ['BTS Biomédical', 'Formation Dialyse'],
                'certifications' => ['Maintenance Dialyse', 'Traitement de l\'eau'],
                'languages' => ['Français', 'Anglais'],
                'hire_date' => '2014-04-01',
                'is_active' => true,
            ],
            
            // Service Néphrologie
            [
                'first_name' => 'Isabelle',
                'last_name' => 'Lefebvre',
                'job_title' => 'Médecin Chef',
                'specialty' => 'Néphrologie',
                'department' => 'Néphrologie',
                'employment_type' => 'full_time',
                'email_pro' => 'isabelle.lefebvre@dispodialyse.fr',
                'phone_office' => '0123456711',
                'phone_mobile' => '0612345611',
                'phone_pager' => '1111',
                'extension' => '201',
                'qualifications' => ['DES Néphrologie', 'HDR', 'PU-PH'],
                'certifications' => ['Chef de Service', 'Recherche Clinique'],
                'languages' => ['Français', 'Anglais', 'Allemand'],
                'hire_date' => '2008-09-01',
                'is_active' => true,
            ],
            [
                'first_name' => 'Jean',
                'last_name' => 'Roux',
                'job_title' => 'Médecin',
                'specialty' => 'Néphrologie',
                'department' => 'Néphrologie',
                'employment_type' => 'full_time',
                'email_pro' => 'jean.roux@dispodialyse.fr',
                'phone_office' => '0123456712',
                'phone_mobile' => '0612345612',
                'extension' => '202',
                'qualifications' => ['DES Néphrologie', 'Master Recherche'],
                'certifications' => ['Transplantation Rénale'],
                'languages' => ['Français', 'Anglais'],
                'hire_date' => '2013-02-01',
                'is_active' => true,
            ],
            [
                'first_name' => 'Laura',
                'last_name' => 'David',
                'job_title' => 'Infirmier',
                'department' => 'Néphrologie',
                'employment_type' => 'full_time',
                'email_pro' => 'laura.david@dispodialyse.fr',
                'phone_mobile' => '0612345613',
                'extension' => '203',
                'qualifications' => ['Diplôme IDE'],
                'languages' => ['Français', 'Italien'],
                'hire_date' => '2019-01-10',
                'is_active' => true,
            ],
            [
                'first_name' => 'Marc',
                'last_name' => 'Bertrand',
                'job_title' => 'Infirmier',
                'department' => 'Néphrologie',
                'employment_type' => 'full_time',
                'email_pro' => 'marc.bertrand@dispodialyse.fr',
                'phone_mobile' => '0612345614',
                'extension' => '204',
                'qualifications' => ['Diplôme IDE', 'DU Néphrologie'],
                'languages' => ['Français'],
                'hire_date' => '2016-08-01',
                'is_active' => true,
            ],
            
            // Service Urgences
            [
                'first_name' => 'Catherine',
                'last_name' => 'Fontaine',
                'job_title' => 'Médecin Urgentiste',
                'specialty' => 'Médecine d\'urgence',
                'department' => 'Urgences',
                'employment_type' => 'full_time',
                'email_pro' => 'catherine.fontaine@dispodialyse.fr',
                'phone_office' => '0123456715',
                'phone_mobile' => '0612345615',
                'phone_pager' => '9999',
                'extension' => '301',
                'qualifications' => ['DES Médecine d\'urgence', 'DESC Réanimation'],
                'certifications' => ['ATLS', 'ACLS'],
                'languages' => ['Français', 'Anglais'],
                'hire_date' => '2011-05-01',
                'is_active' => true,
            ],
            [
                'first_name' => 'Paul',
                'last_name' => 'Chevalier',
                'job_title' => 'Infirmier',
                'department' => 'Urgences',
                'employment_type' => 'full_time',
                'email_pro' => 'paul.chevalier@dispodialyse.fr',
                'phone_mobile' => '0612345616',
                'extension' => '302',
                'qualifications' => ['Diplôme IDE', 'DU Urgences'],
                'certifications' => ['AFGSU 2', 'Tri IAO'],
                'languages' => ['Français'],
                'hire_date' => '2017-10-01',
                'is_active' => true,
            ],
            
            // Service Administration
            [
                'first_name' => 'Sylvie',
                'last_name' => 'Girard',
                'job_title' => 'Directrice Administrative',
                'department' => 'Administration',
                'employment_type' => 'full_time',
                'email_pro' => 'sylvie.girard@dispodialyse.fr',
                'phone_office' => '0123456717',
                'phone_mobile' => '0612345617',
                'extension' => '001',
                'qualifications' => ['Master Gestion Santé', 'MBA'],
                'certifications' => ['Gestion Hospitalière'],
                'languages' => ['Français', 'Anglais'],
                'hire_date' => '2009-01-05',
                'is_active' => true,
            ],
            [
                'first_name' => 'Olivier',
                'last_name' => 'Blanc',
                'job_title' => 'Responsable RH',
                'department' => 'Administration',
                'employment_type' => 'full_time',
                'email_pro' => 'olivier.blanc@dispodialyse.fr',
                'phone_office' => '0123456718',
                'extension' => '002',
                'qualifications' => ['Master RH', 'Droit Social'],
                'languages' => ['Français'],
                'hire_date' => '2014-06-15',
                'is_active' => true,
            ],
            [
                'first_name' => 'Nathalie',
                'last_name' => 'Garnier',
                'job_title' => 'Assistante Administrative',
                'department' => 'Administration',
                'employment_type' => 'full_time',
                'email_pro' => 'nathalie.garnier@dispodialyse.fr',
                'phone_office' => '0123456719',
                'extension' => '003',
                'qualifications' => ['BTS Assistant Manager'],
                'languages' => ['Français', 'Anglais'],
                'hire_date' => '2018-03-01',
                'is_active' => true,
            ],
            [
                'first_name' => 'Éric',
                'last_name' => 'Faure',
                'job_title' => 'Responsable Informatique',
                'department' => 'Administration',
                'employment_type' => 'contractor',
                'email_pro' => 'eric.faure@dispodialyse.fr',
                'phone_office' => '0123456720',
                'phone_mobile' => '0612345620',
                'extension' => '004',
                'qualifications' => ['Ingénieur Informatique', 'Master Cybersécurité'],
                'certifications' => ['CISSP', 'ITIL'],
                'languages' => ['Français', 'Anglais'],
                'hire_date' => '2020-09-01',
                'is_active' => true,
            ],
        ];

        foreach ($personnel as $data) {
            Personnel::create($data);
        }

        $this->command->info('✅ ' . count($personnel) . ' fiches personnel créées avec succès');
    }
}